### ISSUE TITLE
Time Sync Crash

### ISSUE THREAD

**Issue by Aljunier** [OfficialDarkzy/DRP-Core#10]
Hey, when coming upon a new day (transitioning from 23:59 -> 0:00 I think but you get the point), your game will crash with an error known for invalid values being entered in the "NetworkOverrideClockTime" native. So the following is the fix for this that I had working for me. This is located at drp_core -> sync -> server.lua -> lines 69 - 75

This was the fix that worked for me. I'm also not too familiar with Pull Requests so I figured I'd put this here though.
```lua
            if minutes >= 60 and (hours + 1 >= 24) then
                minutes = 0
                hours = 0
            elseif minutes >= 60 then
                hours = hours + 1
                minutes = 0
            end
```

OR you can just change line 72 with
```lua
if hours >= 24 then
```

**Comment by Yumshot** [comment]
Pull Requested it for you , to do so next time , just go to the file you want to make edits to and click the pencil icon. It will allow you to edit the file
