### ISSUE TITLE
Wouldnt Spawn

### ISSUE THREAD

**Issue by dexslab** [OfficialDarkzy/DRP-Core#21]
So after following directions very closely was not able to get spawned in game just stuck at waiting for scripts

**Comment by OhTanoshi** [comment]
you possibly missed a step or didn't configure database?

look at this for how to install https://github.com/OfficialDarkzy/DRP-Core/wiki/How-to-install---Windows

**Comment by dexslab** [comment]
Nope did everything even notice game type is DRP and not drp-core but tried both for good measure

**Comment by OfficialDarkzy** [comment]
Hi Dex, thanks for opening an issue it will require being drp_core as that is the resource name. Please do DM me in discord if you have anymore issue or talk in my discord we are all friendly.
