### ISSUE TITLE
Strange Conflict with vMenu

### ISSUE THREAD

**Issue by shredxt** [OfficialDarkzy/DRP-Core#6]
For some reason, with vMenu enabled the screen flashes white every second, perhaps tied to the tick rate, I'm not entirely sure. I was able to repro on an existing and a fresh server.

**Comment by OfficialDarkzy** [comment]
i have not had this issue and i dont think this is DRP related...

**Comment by Aljunier** [comment]
You must have time sync and/or weather sync enabled in vMenu. Disabling those in the permissions.cfg (i think) should fix the issue.

**Comment by shredxt** [comment]
It's almost definitely the time sync portion of menu conflicting with this. Good find!
